// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvp.Selections.Data;

#nullable disable

namespace Mvp.Selections.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mvp.Selections.Domain.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Eligibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mentor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("MvpTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Objectives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("CountryId");

                    b.HasIndex("MvpTypeId");

                    b.HasIndex("SelectionId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ApplicationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationLinks");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GivenOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RejectedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Country", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Afghanistan "
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Albania "
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Algeria "
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "American Samoa "
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "Andorra "
                        },
                        new
                        {
                            Id = (short)6,
                            Name = "Angola "
                        },
                        new
                        {
                            Id = (short)7,
                            Name = "Anguilla "
                        },
                        new
                        {
                            Id = (short)8,
                            Name = "Antarctica "
                        },
                        new
                        {
                            Id = (short)9,
                            Name = "Antigua and Barbuda "
                        },
                        new
                        {
                            Id = (short)10,
                            Name = "Argentina "
                        },
                        new
                        {
                            Id = (short)11,
                            Name = "Armenia "
                        },
                        new
                        {
                            Id = (short)12,
                            Name = "Aruba "
                        },
                        new
                        {
                            Id = (short)13,
                            Name = "Australia "
                        },
                        new
                        {
                            Id = (short)14,
                            Name = "Austria "
                        },
                        new
                        {
                            Id = (short)15,
                            Name = "Azerbaijan "
                        },
                        new
                        {
                            Id = (short)16,
                            Name = "Bahamas "
                        },
                        new
                        {
                            Id = (short)17,
                            Name = "Bahrain "
                        },
                        new
                        {
                            Id = (short)18,
                            Name = "Bangladesh "
                        },
                        new
                        {
                            Id = (short)19,
                            Name = "Barbados "
                        },
                        new
                        {
                            Id = (short)20,
                            Name = "Belarus "
                        },
                        new
                        {
                            Id = (short)21,
                            Name = "Belgium "
                        },
                        new
                        {
                            Id = (short)22,
                            Name = "Belize "
                        },
                        new
                        {
                            Id = (short)23,
                            Name = "Benin "
                        },
                        new
                        {
                            Id = (short)24,
                            Name = "Bermuda "
                        },
                        new
                        {
                            Id = (short)25,
                            Name = "Bhutan "
                        },
                        new
                        {
                            Id = (short)26,
                            Name = "Bolivia "
                        },
                        new
                        {
                            Id = (short)27,
                            Name = "Bosnia and Herzegovina "
                        },
                        new
                        {
                            Id = (short)28,
                            Name = "Botswana "
                        },
                        new
                        {
                            Id = (short)29,
                            Name = "Bouvet Island "
                        },
                        new
                        {
                            Id = (short)30,
                            Name = "Brazil "
                        },
                        new
                        {
                            Id = (short)31,
                            Name = "British Indian Ocean Territory "
                        },
                        new
                        {
                            Id = (short)32,
                            Name = "Brunei Darussalam "
                        },
                        new
                        {
                            Id = (short)33,
                            Name = "Bulgaria "
                        },
                        new
                        {
                            Id = (short)34,
                            Name = "Burkina Faso "
                        },
                        new
                        {
                            Id = (short)35,
                            Name = "Burundi "
                        },
                        new
                        {
                            Id = (short)36,
                            Name = "Cambodia "
                        },
                        new
                        {
                            Id = (short)37,
                            Name = "Cameroon "
                        },
                        new
                        {
                            Id = (short)38,
                            Name = "Canada "
                        },
                        new
                        {
                            Id = (short)39,
                            Name = "Cape Verde "
                        },
                        new
                        {
                            Id = (short)40,
                            Name = "Cayman Islands "
                        },
                        new
                        {
                            Id = (short)41,
                            Name = "Central African Republic "
                        },
                        new
                        {
                            Id = (short)42,
                            Name = "Chad "
                        },
                        new
                        {
                            Id = (short)43,
                            Name = "Chile "
                        },
                        new
                        {
                            Id = (short)44,
                            Name = "China "
                        },
                        new
                        {
                            Id = (short)45,
                            Name = "Christmas Island "
                        },
                        new
                        {
                            Id = (short)46,
                            Name = "Cocos (Keeling) Islands "
                        },
                        new
                        {
                            Id = (short)47,
                            Name = "Colombia "
                        },
                        new
                        {
                            Id = (short)48,
                            Name = "Comoros "
                        },
                        new
                        {
                            Id = (short)49,
                            Name = "Congo "
                        },
                        new
                        {
                            Id = (short)50,
                            Name = "Congo, The Democratic Republic of The "
                        },
                        new
                        {
                            Id = (short)51,
                            Name = "Cook Islands "
                        },
                        new
                        {
                            Id = (short)52,
                            Name = "Costa Rica "
                        },
                        new
                        {
                            Id = (short)53,
                            Name = "Cote D'ivoire "
                        },
                        new
                        {
                            Id = (short)54,
                            Name = "Croatia "
                        },
                        new
                        {
                            Id = (short)55,
                            Name = "Cuba "
                        },
                        new
                        {
                            Id = (short)56,
                            Name = "Cyprus "
                        },
                        new
                        {
                            Id = (short)57,
                            Name = "Czech Republic "
                        },
                        new
                        {
                            Id = (short)58,
                            Name = "Denmark "
                        },
                        new
                        {
                            Id = (short)59,
                            Name = "Djibouti "
                        },
                        new
                        {
                            Id = (short)60,
                            Name = "Dominica "
                        },
                        new
                        {
                            Id = (short)61,
                            Name = "Dominican Republic "
                        },
                        new
                        {
                            Id = (short)62,
                            Name = "Ecuador "
                        },
                        new
                        {
                            Id = (short)63,
                            Name = "Egypt "
                        },
                        new
                        {
                            Id = (short)64,
                            Name = "El Salvador "
                        },
                        new
                        {
                            Id = (short)65,
                            Name = "Equatorial Guinea "
                        },
                        new
                        {
                            Id = (short)66,
                            Name = "Eritrea "
                        },
                        new
                        {
                            Id = (short)67,
                            Name = "Estonia "
                        },
                        new
                        {
                            Id = (short)68,
                            Name = "Ethiopia "
                        },
                        new
                        {
                            Id = (short)69,
                            Name = "Falkland Islands (Malvinas) "
                        },
                        new
                        {
                            Id = (short)70,
                            Name = "Faroe Islands "
                        },
                        new
                        {
                            Id = (short)71,
                            Name = "Fiji "
                        },
                        new
                        {
                            Id = (short)72,
                            Name = "Finland "
                        },
                        new
                        {
                            Id = (short)73,
                            Name = "France "
                        },
                        new
                        {
                            Id = (short)74,
                            Name = "French Guiana "
                        },
                        new
                        {
                            Id = (short)75,
                            Name = "French Polynesia "
                        },
                        new
                        {
                            Id = (short)76,
                            Name = "French Southern Territories "
                        },
                        new
                        {
                            Id = (short)77,
                            Name = "Gabon "
                        },
                        new
                        {
                            Id = (short)78,
                            Name = "Gambia "
                        },
                        new
                        {
                            Id = (short)79,
                            Name = "Georgia "
                        },
                        new
                        {
                            Id = (short)80,
                            Name = "Germany "
                        },
                        new
                        {
                            Id = (short)81,
                            Name = "Ghana "
                        },
                        new
                        {
                            Id = (short)82,
                            Name = "Gibraltar "
                        },
                        new
                        {
                            Id = (short)83,
                            Name = "Greece "
                        },
                        new
                        {
                            Id = (short)84,
                            Name = "Greenland "
                        },
                        new
                        {
                            Id = (short)85,
                            Name = "Grenada "
                        },
                        new
                        {
                            Id = (short)86,
                            Name = "Guadeloupe "
                        },
                        new
                        {
                            Id = (short)87,
                            Name = "Guam "
                        },
                        new
                        {
                            Id = (short)88,
                            Name = "Guatemala "
                        },
                        new
                        {
                            Id = (short)89,
                            Name = "Guinea "
                        },
                        new
                        {
                            Id = (short)90,
                            Name = "Guinea-bissau "
                        },
                        new
                        {
                            Id = (short)91,
                            Name = "Guyana "
                        },
                        new
                        {
                            Id = (short)92,
                            Name = "Haiti "
                        },
                        new
                        {
                            Id = (short)93,
                            Name = "Heard Island and Mcdonald Islands "
                        },
                        new
                        {
                            Id = (short)94,
                            Name = "Holy See (Vatican City State) "
                        },
                        new
                        {
                            Id = (short)95,
                            Name = "Honduras "
                        },
                        new
                        {
                            Id = (short)96,
                            Name = "Hong Kong "
                        },
                        new
                        {
                            Id = (short)97,
                            Name = "Hungary "
                        },
                        new
                        {
                            Id = (short)98,
                            Name = "Iceland "
                        },
                        new
                        {
                            Id = (short)99,
                            Name = "India "
                        },
                        new
                        {
                            Id = (short)100,
                            Name = "Indonesia "
                        },
                        new
                        {
                            Id = (short)101,
                            Name = "Iran, Islamic Republic of "
                        },
                        new
                        {
                            Id = (short)102,
                            Name = "Iraq "
                        },
                        new
                        {
                            Id = (short)103,
                            Name = "Ireland "
                        },
                        new
                        {
                            Id = (short)104,
                            Name = "Israel "
                        },
                        new
                        {
                            Id = (short)105,
                            Name = "Italy "
                        },
                        new
                        {
                            Id = (short)106,
                            Name = "Jamaica "
                        },
                        new
                        {
                            Id = (short)107,
                            Name = "Japan "
                        },
                        new
                        {
                            Id = (short)108,
                            Name = "Jordan "
                        },
                        new
                        {
                            Id = (short)109,
                            Name = "Kazakhstan "
                        },
                        new
                        {
                            Id = (short)110,
                            Name = "Kenya "
                        },
                        new
                        {
                            Id = (short)111,
                            Name = "Kiribati "
                        },
                        new
                        {
                            Id = (short)112,
                            Name = "Korea, Democratic People's Republic of "
                        },
                        new
                        {
                            Id = (short)113,
                            Name = "Korea, Republic of "
                        },
                        new
                        {
                            Id = (short)114,
                            Name = "Kuwait "
                        },
                        new
                        {
                            Id = (short)115,
                            Name = "Kyrgyzstan "
                        },
                        new
                        {
                            Id = (short)116,
                            Name = "Lao People's Democratic Republic "
                        },
                        new
                        {
                            Id = (short)117,
                            Name = "Latvia "
                        },
                        new
                        {
                            Id = (short)118,
                            Name = "Lebanon "
                        },
                        new
                        {
                            Id = (short)119,
                            Name = "Lesotho "
                        },
                        new
                        {
                            Id = (short)120,
                            Name = "Liberia "
                        },
                        new
                        {
                            Id = (short)121,
                            Name = "Libyan Arab Jamahiriya "
                        },
                        new
                        {
                            Id = (short)122,
                            Name = "Liechtenstein "
                        },
                        new
                        {
                            Id = (short)123,
                            Name = "Lithuania "
                        },
                        new
                        {
                            Id = (short)124,
                            Name = "Luxembourg "
                        },
                        new
                        {
                            Id = (short)125,
                            Name = "Macao "
                        },
                        new
                        {
                            Id = (short)126,
                            Name = "North Macedonia "
                        },
                        new
                        {
                            Id = (short)127,
                            Name = "Madagascar "
                        },
                        new
                        {
                            Id = (short)128,
                            Name = "Malawi "
                        },
                        new
                        {
                            Id = (short)129,
                            Name = "Malaysia "
                        },
                        new
                        {
                            Id = (short)130,
                            Name = "Maldives "
                        },
                        new
                        {
                            Id = (short)131,
                            Name = "Mali "
                        },
                        new
                        {
                            Id = (short)132,
                            Name = "Malta "
                        },
                        new
                        {
                            Id = (short)133,
                            Name = "Marshall Islands "
                        },
                        new
                        {
                            Id = (short)134,
                            Name = "Martinique "
                        },
                        new
                        {
                            Id = (short)135,
                            Name = "Mauritania "
                        },
                        new
                        {
                            Id = (short)136,
                            Name = "Mauritius "
                        },
                        new
                        {
                            Id = (short)137,
                            Name = "Mayotte "
                        },
                        new
                        {
                            Id = (short)138,
                            Name = "Mexico "
                        },
                        new
                        {
                            Id = (short)139,
                            Name = "Micronesia, Federated States of "
                        },
                        new
                        {
                            Id = (short)140,
                            Name = "Moldova, Republic of "
                        },
                        new
                        {
                            Id = (short)141,
                            Name = "Monaco "
                        },
                        new
                        {
                            Id = (short)142,
                            Name = "Mongolia "
                        },
                        new
                        {
                            Id = (short)143,
                            Name = "Montserrat "
                        },
                        new
                        {
                            Id = (short)144,
                            Name = "Morocco "
                        },
                        new
                        {
                            Id = (short)145,
                            Name = "Mozambique "
                        },
                        new
                        {
                            Id = (short)146,
                            Name = "Myanmar "
                        },
                        new
                        {
                            Id = (short)147,
                            Name = "Namibia "
                        },
                        new
                        {
                            Id = (short)148,
                            Name = "Nauru "
                        },
                        new
                        {
                            Id = (short)149,
                            Name = "Nepal "
                        },
                        new
                        {
                            Id = (short)150,
                            Name = "Netherlands "
                        },
                        new
                        {
                            Id = (short)151,
                            Name = "Netherlands Antilles "
                        },
                        new
                        {
                            Id = (short)152,
                            Name = "New Caledonia "
                        },
                        new
                        {
                            Id = (short)153,
                            Name = "New Zealand "
                        },
                        new
                        {
                            Id = (short)154,
                            Name = "Nicaragua "
                        },
                        new
                        {
                            Id = (short)155,
                            Name = "Niger "
                        },
                        new
                        {
                            Id = (short)156,
                            Name = "Nigeria "
                        },
                        new
                        {
                            Id = (short)157,
                            Name = "Niue "
                        },
                        new
                        {
                            Id = (short)158,
                            Name = "Norfolk Island "
                        },
                        new
                        {
                            Id = (short)159,
                            Name = "Northern Mariana Islands "
                        },
                        new
                        {
                            Id = (short)160,
                            Name = "Norway "
                        },
                        new
                        {
                            Id = (short)161,
                            Name = "Oman "
                        },
                        new
                        {
                            Id = (short)162,
                            Name = "Pakistan "
                        },
                        new
                        {
                            Id = (short)163,
                            Name = "Palau "
                        },
                        new
                        {
                            Id = (short)164,
                            Name = "Palestinian Territory, Occupied "
                        },
                        new
                        {
                            Id = (short)165,
                            Name = "Panama "
                        },
                        new
                        {
                            Id = (short)166,
                            Name = "Papua New Guinea "
                        },
                        new
                        {
                            Id = (short)167,
                            Name = "Paraguay "
                        },
                        new
                        {
                            Id = (short)168,
                            Name = "Peru "
                        },
                        new
                        {
                            Id = (short)169,
                            Name = "Philippines "
                        },
                        new
                        {
                            Id = (short)170,
                            Name = "Pitcairn "
                        },
                        new
                        {
                            Id = (short)171,
                            Name = "Poland "
                        },
                        new
                        {
                            Id = (short)172,
                            Name = "Portugal "
                        },
                        new
                        {
                            Id = (short)173,
                            Name = "Puerto Rico "
                        },
                        new
                        {
                            Id = (short)174,
                            Name = "Qatar "
                        },
                        new
                        {
                            Id = (short)175,
                            Name = "Reunion "
                        },
                        new
                        {
                            Id = (short)176,
                            Name = "Romania "
                        },
                        new
                        {
                            Id = (short)177,
                            Name = "Russian Federation "
                        },
                        new
                        {
                            Id = (short)178,
                            Name = "Rwanda "
                        },
                        new
                        {
                            Id = (short)179,
                            Name = "Saint Helena "
                        },
                        new
                        {
                            Id = (short)180,
                            Name = "Saint Kitts and Nevis "
                        },
                        new
                        {
                            Id = (short)181,
                            Name = "Saint Lucia "
                        },
                        new
                        {
                            Id = (short)182,
                            Name = "Saint Pierre and Miquelon "
                        },
                        new
                        {
                            Id = (short)183,
                            Name = "Saint Vincent and The Grenadines "
                        },
                        new
                        {
                            Id = (short)184,
                            Name = "Samoa "
                        },
                        new
                        {
                            Id = (short)185,
                            Name = "San Marino "
                        },
                        new
                        {
                            Id = (short)186,
                            Name = "Sao Tome and Principe "
                        },
                        new
                        {
                            Id = (short)187,
                            Name = "Saudi Arabia "
                        },
                        new
                        {
                            Id = (short)188,
                            Name = "Senegal "
                        },
                        new
                        {
                            Id = (short)189,
                            Name = "Serbia and Montenegro "
                        },
                        new
                        {
                            Id = (short)190,
                            Name = "Seychelles "
                        },
                        new
                        {
                            Id = (short)191,
                            Name = "Sierra Leone "
                        },
                        new
                        {
                            Id = (short)192,
                            Name = "Singapore "
                        },
                        new
                        {
                            Id = (short)193,
                            Name = "Slovakia "
                        },
                        new
                        {
                            Id = (short)194,
                            Name = "Slovenia "
                        },
                        new
                        {
                            Id = (short)195,
                            Name = "Solomon Islands "
                        },
                        new
                        {
                            Id = (short)196,
                            Name = "Somalia "
                        },
                        new
                        {
                            Id = (short)197,
                            Name = "South Africa "
                        },
                        new
                        {
                            Id = (short)198,
                            Name = "South Georgia and The South Sandwich Islands "
                        },
                        new
                        {
                            Id = (short)199,
                            Name = "Spain "
                        },
                        new
                        {
                            Id = (short)200,
                            Name = "Sri Lanka "
                        },
                        new
                        {
                            Id = (short)201,
                            Name = "Sudan "
                        },
                        new
                        {
                            Id = (short)202,
                            Name = "Suriname "
                        },
                        new
                        {
                            Id = (short)203,
                            Name = "Svalbard and Jan Mayen "
                        },
                        new
                        {
                            Id = (short)204,
                            Name = "Swaziland "
                        },
                        new
                        {
                            Id = (short)205,
                            Name = "Sweden "
                        },
                        new
                        {
                            Id = (short)206,
                            Name = "Switzerland "
                        },
                        new
                        {
                            Id = (short)207,
                            Name = "Syrian Arab Republic "
                        },
                        new
                        {
                            Id = (short)208,
                            Name = "Taiwan, Province of China "
                        },
                        new
                        {
                            Id = (short)209,
                            Name = "Tajikistan "
                        },
                        new
                        {
                            Id = (short)210,
                            Name = "Tanzania, United Republic of "
                        },
                        new
                        {
                            Id = (short)211,
                            Name = "Thailand "
                        },
                        new
                        {
                            Id = (short)212,
                            Name = "Timor-leste "
                        },
                        new
                        {
                            Id = (short)213,
                            Name = "Togo "
                        },
                        new
                        {
                            Id = (short)214,
                            Name = "Tokelau "
                        },
                        new
                        {
                            Id = (short)215,
                            Name = "Tonga "
                        },
                        new
                        {
                            Id = (short)216,
                            Name = "Trinidad and Tobago "
                        },
                        new
                        {
                            Id = (short)217,
                            Name = "Tunisia "
                        },
                        new
                        {
                            Id = (short)218,
                            Name = "Turkey "
                        },
                        new
                        {
                            Id = (short)219,
                            Name = "Turkmenistan "
                        },
                        new
                        {
                            Id = (short)220,
                            Name = "Turks and Caicos Islands "
                        },
                        new
                        {
                            Id = (short)221,
                            Name = "Tuvalu "
                        },
                        new
                        {
                            Id = (short)222,
                            Name = "Uganda "
                        },
                        new
                        {
                            Id = (short)223,
                            Name = "Ukraine "
                        },
                        new
                        {
                            Id = (short)224,
                            Name = "United Arab Emirates "
                        },
                        new
                        {
                            Id = (short)225,
                            Name = "United Kingdom "
                        },
                        new
                        {
                            Id = (short)226,
                            Name = "United States "
                        },
                        new
                        {
                            Id = (short)227,
                            Name = "United States Minor Outlying Islands "
                        },
                        new
                        {
                            Id = (short)228,
                            Name = "Uruguay "
                        },
                        new
                        {
                            Id = (short)229,
                            Name = "Uzbekistan "
                        },
                        new
                        {
                            Id = (short)230,
                            Name = "Vanuatu "
                        },
                        new
                        {
                            Id = (short)231,
                            Name = "Venezuela "
                        },
                        new
                        {
                            Id = (short)232,
                            Name = "Viet Nam "
                        },
                        new
                        {
                            Id = (short)233,
                            Name = "Virgin Islands, British "
                        },
                        new
                        {
                            Id = (short)234,
                            Name = "Virgin Islands, U.S. "
                        },
                        new
                        {
                            Id = (short)235,
                            Name = "Wallis and Futuna "
                        },
                        new
                        {
                            Id = (short)236,
                            Name = "Western Sahara "
                        },
                        new
                        {
                            Id = (short)237,
                            Name = "Yemen "
                        },
                        new
                        {
                            Id = (short)238,
                            Name = "Zambia "
                        },
                        new
                        {
                            Id = (short)239,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Mvp.Selections.Domain.MvpType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MvpType");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("ApplicationLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationLinkId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ProfileLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProfileLinks");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ReviewCategoryScore", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScoreCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId", "ScoreCategoryId", "ScoreId");

                    b.HasIndex("ScoreCategoryId");

                    b.HasIndex("ScoreId");

                    b.ToTable("ReviewCategoryScore");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Role");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScoreCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScoreCategoryId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ScoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("MvpTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MvpTypeId");

                    b.HasIndex("SelectionId");

                    b.ToTable("ScoreCategories");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Selection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ApplicationsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ApplicationsEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ApplicationsStart")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ReviewsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReviewsEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReviewsStart")
                        .HasColumnType("datetime2");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Selections");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("MvpTypeId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Warning")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("MvpTypeId");

                    b.HasIndex("SelectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CountryId = (short)21,
                            Identifier = "00uid4BxXw6I6TV4m0g3",
                            ImageType = 0
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Mvp.Selections.Domain.SelectionRole", b =>
                {
                    b.HasBaseType("Mvp.Selections.Domain.Role");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("CountryId")
                        .HasColumnType("smallint");

                    b.Property<short?>("MvpTypeId")
                        .HasColumnType("smallint");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<Guid?>("SelectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CountryId");

                    b.HasIndex("MvpTypeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SelectionId");

                    b.HasDiscriminator().HasValue("SelectionRole");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.SystemRole", b =>
                {
                    b.HasBaseType("Mvp.Selections.Domain.Role");

                    b.Property<int>("Rights")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SystemRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Admin",
                            Rights = 1
                        });
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Application", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.User", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.MvpType", "MvpType")
                        .WithMany()
                        .HasForeignKey("MvpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.Selection", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Country");

                    b.Navigation("MvpType");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ApplicationLink", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Application", null)
                        .WithMany("Links")
                        .HasForeignKey("ApplicationId");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Consent", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.User", "User")
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Country", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Product", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.ApplicationLink", null)
                        .WithMany("RelatedProducts")
                        .HasForeignKey("ApplicationLinkId");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ProfileLink", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.User", null)
                        .WithMany("Links")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Review", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Application", "Application")
                        .WithMany("Reviews")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ReviewCategoryScore", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Review", "Review")
                        .WithMany("CategoryScores")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.ScoreCategory", "ScoreCategory")
                        .WithMany()
                        .HasForeignKey("ScoreCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.Score", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Score");

                    b.Navigation("ScoreCategory");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Score", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.ScoreCategory", null)
                        .WithMany("ScoreOptions")
                        .HasForeignKey("ScoreCategoryId");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ScoreCategory", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.MvpType", "MvpType")
                        .WithMany()
                        .HasForeignKey("MvpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.Selection", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MvpType");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Title", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.MvpType", "MvpType")
                        .WithMany()
                        .HasForeignKey("MvpTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.Selection", "Selection")
                        .WithMany("Titles")
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.User", "User")
                        .WithMany("Titles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("MvpType");

                    b.Navigation("Selection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.User", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.User", null)
                        .WithMany("Mentors")
                        .HasForeignKey("UserId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvp.Selections.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mvp.Selections.Domain.SelectionRole", b =>
                {
                    b.HasOne("Mvp.Selections.Domain.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId");

                    b.HasOne("Mvp.Selections.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Mvp.Selections.Domain.MvpType", "MvpType")
                        .WithMany()
                        .HasForeignKey("MvpTypeId");

                    b.HasOne("Mvp.Selections.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("Mvp.Selections.Domain.Selection", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId");

                    b.Navigation("Application");

                    b.Navigation("Country");

                    b.Navigation("MvpType");

                    b.Navigation("Region");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Application", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ApplicationLink", b =>
                {
                    b.Navigation("RelatedProducts");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Country", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Region", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Review", b =>
                {
                    b.Navigation("CategoryScores");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.ScoreCategory", b =>
                {
                    b.Navigation("ScoreOptions");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.Selection", b =>
                {
                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Mvp.Selections.Domain.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Consents");

                    b.Navigation("Links");

                    b.Navigation("Mentors");

                    b.Navigation("Reviews");

                    b.Navigation("Titles");
                });
#pragma warning restore 612, 618
        }
    }
}
