<Project>

  <!--<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />-->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup Label="Shared Assets">
    <Compile Include="$(MSBuildThisFileDirectory)GlobalSuppressions.cs">
      <Link>GlobalSuppressions.cs</Link>
    </Compile>
  </ItemGroup>

</Project>